version: "3.5"
services: 

  postgres:
    container_name: postgresIntegr
    image: postgres
    restart: always
    volumes:
      - ./database/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 5438:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080